from __future__ import annotations

from copy import deepcopy
from typing import Any

import pytest


GENERATION = {
    "generator_version": "1.0.0",
    "seed": 42017,
    "source_rule_ids": ["rule.cs.ay2026"],
}


def valid_payloads() -> dict[str, dict[str, Any]]:
    path = {
        "path_id": "path.standard",
        "steps": [
            {
                "step_id": "step.audit",
                "action": "Run the deterministic degree audit",
                "parameters": {"student_id": "SIM-CS-001"},
                "requires_approval": False,
            }
        ],
        "rationale": "The audit establishes the outstanding requirement.",
        "source_rule_ids": ["rule.cs.ay2026"],
    }
    return {
        "source": {
            "source_id": "source.curriculum.cs.2026",
            "source_type": "curriculum",
            "programme": "CS",
            "admission_cohort": "2023",
            "effective_academic_year": "AY2026-27",
            "offering_academic_year": None,
            "source_url": "https://www.ntu.edu.sg/example/curriculum",
            "retrieved_at": "2026-08-30T12:00:00+08:00",
            "checked_at": "2026-08-30T12:00:00+08:00",
            "version": "2026.1",
            "origin": "VERIFIED_REAL",
            "access_status": "RETRIEVED",
            "classification": "PUBLIC",
            "retrieval_method": "DIRECT_DOWNLOAD",
            "request_parameters": {},
            "content_sha256": "0" * 64,
            "checksum_scope": "SOURCE_BYTES",
            "access_note": None,
            "effective_from": "2026-08-01",
            "effective_to": None,
            "dependent_records": ["curriculum.cs.2023"],
        },
        "programme": {
            "programme_id": "programme.cs",
            "code": "CS",
            "name": "Computer Science",
            "college": "College of Computing and Data Science",
            "programme_kind": "SINGLE_DEGREE",
            "study_mode": "FULL_TIME",
            "ccds_base_programmes": [],
            "external_identifiers": {"portal": "CS"},
            "active": True,
            "source_ids": ["source.curriculum.cs.2026"],
        },
        "curriculum": {
            "curriculum_id": "curriculum.cs.2023",
            "name": "Computer Science AY2023 curriculum",
            "programme": "CS",
            "configuration_kind": "BASE",
            "additional_applicable_programmes": [],
            "admission_cohort": "2023",
            "effective_academic_year": "AY2026-27",
            "graduation_aus": "120",
            "requirements": [
                {
                    "requirement_id": "requirement.cs.core",
                    "name": "Core requirement",
                    "category": "CORE",
                    "minimum_aus": "3",
                    "minimum_courses": 1,
                    "required_courses": ["SC1001"],
                    "elective_pool": [],
                    "constraints": [],
                    "course_lists_completeness": "COMPLETE",
                }
            ],
            "study_plan": [
                {
                    "plan_item_id": "plan.cs.y1s1.sc1001",
                    "study_year": 1,
                    "semester": "SEMESTER_1",
                    "position": 1,
                    "course_code": "SC1001",
                    "raw_course_code": "SC1001",
                    "label": "Introduction to Computing",
                    "category": "CORE",
                    "aus": "3",
                    "requirement_id": "requirement.cs.core",
                    "notes": [],
                    "source_ids": ["source.curriculum.cs.2026"],
                }
            ],
            "programme_constraints": [],
            "rules_completeness": "COMPLETE",
            "known_gaps": [],
            "unavailable_reason": None,
            "source_ids": ["source.curriculum.cs.2026"],
        },
        "course": {
            "code": "SC1001",
            "title": "Introduction to Computing",
            "aus": "3",
            "prerequisites": {
                "all_of": [],
                "any_of": [],
                "minimum_study_year": None,
                "raw_text": None,
            },
            "exclusions": ["CE1001"],
            "exclusions_raw_text": "CE1001",
            "catalogue_appearances": [
                {
                    "academic_year": "AY2026-27",
                    "semester": "SEMESTER_1",
                    "catalogue_context": "PROGRAMME",
                    "programme": "CS",
                    "study_years": [1],
                    "source_ids": ["source.course.sc1001"],
                }
            ],
            "applicable_programmes": ["CS"],
            "programme_categories": {"CS": ["CORE"]},
            "documented_constraints": [],
            "prerequisites_completeness": "COMPLETE",
            "exclusions_completeness": "PARTIAL",
            "applicability_completeness": "COMPLETE",
            "constraints_completeness": "UNKNOWN",
            "source_ids": ["source.course.sc1001"],
        },
        "offering": {
            "offering_id": "offering.sc1001.ay2026.s1",
            "course_code": "SC1001",
            "academic_year": "AY2026-27",
            "semester": "SEMESTER_1",
            "status": "OFFERED",
            "observed_programmes": ["CS"],
            "scope_completeness": "COMPLETE",
            "indexes": [
                {
                    "index_id": "10001",
                    "observed_programmes": ["CS"],
                    "meetings": [
                        {
                            "class_type": "LECTURE",
                            "day": "MONDAY",
                            "start_time": "09:00:00",
                            "end_time": "11:00:00",
                            "venue": "LT1",
                            "teaching_weeks": [1, 2, 3],
                        }
                    ],
                    "capacity": None,
                    "vacancies": None,
                    "waitlist_count": None,
                }
            ],
            "snapshot_at": "2026-08-30T12:00:00+08:00",
            "source_ids": ["source.offering.sc1001.ay2026.s1"],
        },
        "offering_state": {
            "state_id": "offering-state.sc1001.10001.v1",
            "simulation_period_id": "period.terminal.s1",
            "template_offering_id": "offering.sc1001.ay2026.s1",
            "template_index_id": "10001",
            "template_academic_year": "AY2026-27",
            "template_semester": "SEMESTER_1",
            "capacity": 30,
            "vacancies": 4,
            "waitlist_count": 0,
            "runtime_status": "OPEN",
            "available": True,
            "unavailable_reason": None,
            "version": 1,
            "assumption_ids": ["assumption.offering-state.default"],
            **GENERATION,
        },
        "student": {
            "student_id": "SIM-CS-001",
            "simulation_scope_id": "scope.cs.2023",
            "simulation_period_id": "period.terminal.s1",
            "programme": "CS",
            "additional_programmes": [],
            "curriculum_id": "curriculum.cs.2023",
            "graduation_path_id": None,
            "study_plan_path_label": None,
            "admission_cohort": "2023",
            "study_year": 4,
            "terminal_profile": "REQUIREMENT_OUTSTANDING",
            "academic_standing": "GOOD_STANDING",
            "has_outstanding_fees": False,
            "completed_courses": [
                {
                    "course_code": "SC1001",
                    "grade": "A",
                    "aus_earned": "3",
                    "credit_status": "EARNED",
                    "academic_year": "AY2025-26",
                    "semester": "SEMESTER_2",
                    "attempt": 1,
                }
            ],
            "earned_aus": "3",
            "exemptions": [],
            "assumption_ids": [],
            **GENERATION,
        },
        "audit": {
            "audit_id": "audit.sim.cs.001",
            "student_id": "SIM-CS-001",
            "simulation_scope_id": "scope.cs.2023",
            "simulation_period_id": "period.terminal.s1",
            "curriculum_id": "curriculum.cs.2023",
            "audit_basis": "SCENARIO_BOUNDED_SIMULATION",
            "audit_outcome": "READY",
            "graduation_path_id": None,
            "study_plan_path_label": None,
            "simulation_academic_year": "AY2028-29",
            "semester": "SEMESTER_1",
            "requirement_results": [
                {
                    "requirement_id": "requirement.cs.core",
                    "status": "SATISFIED",
                    "required_aus": "3",
                    "earned_aus": "3",
                    "completed_courses": ["SC1001"],
                    "outstanding_courses": [],
                    "explanation": "The required course is complete.",
                    "evidence_rule_ids": ["requirement.cs.core"],
                    "assumption_ids": [],
                    "limitations": [],
                }
            ],
            "total_earned_aus": "3",
            "total_required_aus": "3",
            "assumption_ids": [],
            "limitations": [],
            **GENERATION,
        },
        "registration": {
            "registration_id": "registration.sim.cs.001",
            "student_id": "SIM-CS-001",
            "simulation_scope_id": "scope.cs.2023",
            "simulation_period_id": "period.terminal.s1",
            "simulation_academic_year": "AY2028-29",
            "semester": "SEMESTER_1",
            "template_academic_year": "AY2026-27",
            "template_semester": "SEMESTER_1",
            "scenario_time": "2028-08-30T12:00:00+08:00",
            "phase": "POST_ADD_DROP",
            "registered_courses": [
                {
                    "registration_item_id": "registration-item.sim.cs.001.sc1001",
                    "course_code": "SC1001",
                    "template_offering_id": "offering.sc1001.ay2026.s1",
                    "template_index_id": "10001",
                    "offering_state_id": "offering-state.sc1001.10001.v1",
                    "expected_state_version": 1,
                    "aus": "3",
                    "status": "REGISTERED",
                    "eligibility": "ELIGIBLE",
                    "eligibility_reason": "Eligible in the bounded simulation.",
                }
            ],
            "timetable": [],
            "workload_aus": "3",
            "workload_limit_aus": "21",
            "missing_required_courses": [],
            "assumption_ids": [],
            **GENERATION,
        },
        "case": {
            "case_id": "case.sim.001",
            "student_id": "SIM-CS-001",
            "simulation_scope_id": "scope.cs.2023",
            "audit_id": "audit.sim.cs.001",
            "registration_id": "registration.sim.cs.001",
            "scenario_time": "2028-08-30T12:00:00+08:00",
            "problem_type": "REGISTRATION_AFTER_DEADLINE",
            "reason": "A required registration issue was found after Add/Drop.",
            "goal": "Identify a valid path to satisfy the requirement.",
            "requested_action": "Assess the correct exception process.",
            "policy_section_ids": ["policy.registration.section.001"],
            "assumption_ids": [],
            "supporting_documents": [],
            "evidence": [
                {
                    "evidence_id": "evidence.audit.001",
                    "evidence_type": "DEGREE_AUDIT",
                    "reference": "audit.sim.cs.001",
                    "source_id": None,
                }
            ],
            "state": "OPEN",
            "created_at": "2028-08-30T12:00:00+08:00",
            **GENERATION,
        },
        "approval": {
            "approval_id": "approval.sim.001",
            "case_id": "case.sim.001",
            "simulation_scope_id": "scope.cs.2023",
            "approver_role": "School undergraduate office",
            "requested_action": "Approve late registration review",
            "status": "PENDING",
            "observable": False,
            "basis": "SIMULATED_POLICY",
            "basis_rule_ids": ["policy.prototype.late-registration.v1"],
            "version": 1,
            "required_document_ids": [],
            "decision_reason": None,
            "requested_at": "2028-08-30T12:00:00+08:00",
            "decided_at": None,
            **GENERATION,
        },
        "transaction": {
            "transaction_id": "transaction.sim.001",
            "case_id": "case.sim.001",
            "action": "SUBMIT_REGISTRATION",
            "action_parameters": {
                "course_code": "SC1001",
                "template_index_id": "10001"
            },
            "attempt_number": 1,
            "result_code": "SUCCESS",
            "observation": "TRANSACTION_SUCCESS",
            "retryable": False,
            "message": "Registration completed in the simulator.",
            "error_code": None,
            "event": None,
            "precondition_state_versions": {},
            "mutations": [],
            "occurred_at": "2028-08-30T12:05:00+08:00",
            **GENERATION,
        },
        "transaction_script": {
            "script_id": "script.sim.001",
            "case_id": "case.sim.001",
            "simulation_scope_id": "scope.cs.2023",
            "steps": [],
            **GENERATION,
        },
        "scenario": {
            "scenario_id": "S1-D01",
            "family": "S1",
            "split": "development",
            "simulation_scope_id": "scope.cs.2023",
            "student_id": "SIM-CS-001",
            "curriculum_id": "curriculum.cs.2023",
            "audit_id": "audit.sim.cs.001",
            "registration_id": "registration.sim.cs.001",
            "case_id": "case.sim.001",
            "offering_state_ids": ["offering-state.sc1001.10001.v1"],
            "transaction_script_id": "script.sim.001",
            "initial_state_refs": [
                "audit.sim.cs.001",
                "registration.sim.cs.001",
            ],
            "initial_state": {"request_received": True},
            "injected_event": None,
            "ground_truth": {
                "valid_initial_paths": [path],
                "valid_final_paths": [],
                "invalid_paths": [],
                "requires_human": False,
                "expected_outcome": "RESOLVED",
            },
            **GENERATION,
        },
        "generation_manifest": {
            "manifest_id": "manifest.stage3.v1",
            "generator_version": "1.0.0",
            "global_seed": 42017,
            "generated_at": "2026-08-31T12:00:00+08:00",
            "coverage_contract_id": "coverage.stage2.v1",
            "real_data_hashes": {"courses": "0" * 64},
            "source_rule_ids": ["rule.cs.ay2026"],
            "simulation_period_ids": ["period.terminal.s1"],
            "simulation_period_rule": "Map each scope to its terminal-stage year.",
            "prototype_policies": [
                {
                    "policy_id": "policy.prototype.late-registration",
                    "title": "Prototype late-registration route",
                    "origin": "SIMULATED_POLICY",
                    "body_markdown": (
                        "SIMULATED POLICY FOR PROTOTYPE\n\n"
                        "A fictional review route used only by the simulator."
                    ),
                    "applicable_academic_years": ["AY2028-29"],
                    "applicable_admission_cohorts": ["2023"],
                    "applicability_note": "Only the declared CS simulation scope.",
                    "version": "1.0.0",
                    **GENERATION,
                }
            ],
            "prototype_policy_versions": {
                "policy.prototype.late-registration": "1.0.0"
            },
            "record_counts": {"students": 240, "offering_states": 2108},
        },
        "simulation_scope": {
            "simulation_scope_id": "scope.cs.2023",
            "curriculum_id": "curriculum.cs.2023",
            "programme": "CS",
            "admission_cohort": "2023",
            "simulation_period_id": "period.terminal.s1",
            "simulation_academic_year": "AY2028-29",
            "simulation_semester": "SEMESTER_1",
            "template_academic_year": "AY2026-27",
            "template_semester": "SEMESTER_1",
            "terminal_study_year": 4,
            "student_count": 21,
            "audit_basis": "SCENARIO_BOUNDED_SIMULATION",
            "counterfactual_time_basis": "AY2026-27 is a timetable template only.",
            "permitted_graduation_path_ids": [],
            "permitted_study_plan_path_labels": [],
            "accepted_gap_ids": ["gap.course-categories"],
            "assumption_ids": ["assumption.cs.core-map"],
            **GENERATION,
        },
        "audit_assumption": {
            "assumption_id": "assumption.cs.core-map",
            "simulation_scope_id": "scope.cs.2023",
            "kind": "SOURCE_BACKED_DERIVATION",
            "description": "Use the typed study-plan requirement link.",
            "declared_value": {"requirement_id": "requirement.cs.core"},
            "affected_record_ids": ["audit.sim.cs.001"],
            "limitations": [],
            "prototype_policy_id": None,
            **GENERATION,
        },
        "prototype_policy": {
            "policy_id": "policy.prototype.late-registration",
            "title": "Prototype late-registration route",
            "origin": "SIMULATED_POLICY",
            "body_markdown": (
                "SIMULATED POLICY FOR PROTOTYPE\n\n"
                "A fictional review route used only by the simulator."
            ),
            "applicable_academic_years": ["AY2028-29"],
            "applicable_admission_cohorts": ["2023"],
            "applicability_note": "Only the declared CS simulation scope.",
            "version": "1.0.0",
            **GENERATION,
        },
    }


@pytest.fixture
def payloads() -> dict[str, dict[str, Any]]:
    values = valid_payloads()
    values["transaction_script"]["steps"] = [deepcopy(values["transaction"])]
    return values
