export type Rect = {x: number; y: number; width: number; height: number};
export type Camera = {x: number; y: number; scale: number};
export type Shot = {id: string; scenarioId: string; nodeId?: string; attempt?: number; phase?: string; seconds: number; focus: string; speech?: string};
export type Clip = {sourceStart: number; sourceEnd: number; target: Rect; highlight: Rect; interaction?: {at: number; target: Rect; highlight: Rect}; scenarioId: string; nodeId: string | null; attempt: number | null};
export type Take = {schemaVersion: number; footage: string; viewport: {width: number; height: number}; shots: Record<string, Clip>; runs: Record<string, {status: string; approvalPerformed: boolean}>};
export const FPS: number;
export function buildTimeline(edit: Shot[]): (Shot & {start: number; duration: number})[];
export function validateTake(edit: Shot[], take: Take): Take;
export function cameraFor(target: Rect, source: Take['viewport']): Camera;
export function moveCamera(from: Camera, to: Camera, frame: number, fps?: number): Camera;
